import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen relative`}>
        <div className="absolute top-0 left-0 w-full lg:w-[70%] h-[640px] rounded-br-[40px] bg-gradient-to-r from-white to-[#acbedb]"></div>
        {children}
      </body>
    </html>
  );
}
